
spring:
  datasource:
    password:
    username: sa
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate:
      ddl-auto: create
  # http://localhost:8080/h2-console/
  h2:
    console:
      enabled: true

logging:
  level:
    root: info
    org.springframework: info
    ru.steklopod: debug

#  jackson:
#    serialization:
#      indent_output: true
#  profiles:
#    active: development
#    include: swagger
#server:
#  port: 8888
#  compression:
#    enabled: true
#    mime-types: application/json
#  servlet:
#    session:
#      cookie:
#        http-only: true
